<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class BlogsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('blogs')->insert([
            [
                'id' => 1,
                'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
                'slug' => 'w',
                'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
                'author_name' => 'No',
                'author_bio' => '',
                'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
                'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
                'original_content' => null,
                'tags' => '["Beginner","Market"]',
                'keys' => null,
                'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
                'user_id' => 1,
                'blog_category_id' => 1,
                'read_time' => '5 min',
                'status' => 'draft',
                'featured' => 0,
                'seo_title' => 'w | Blog',
                'seo_description' => 'w',
                'seo_keywords' => 'Beginner',
                'publish_date' => '2026-01-30',
                'created_at' => '2026-01-31 06:40:33',
                'updated_at' => '2026-01-31 06:53:45',
            ],
        ]);
    }
}


//large
// namespace Database\Seeders;

// use Illuminate\Database\Seeder;
// use Illuminate\Support\Facades\DB;
// use Carbon\Carbon;

// class BlogsTableSeeder extends Seeder
// {
//     /**
//      * Run the database seeds.
//      */
//     public function run(): void
//     {
//         DB::table('blogs')->insert([
//             [
//                 'id' => 1,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 2,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 3,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 4,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 5,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 6,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 7,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 8,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 9,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 10,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 11,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 13,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 14,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],[
//                 'id' => 15,
//                 'title' => 'Assisted Living for Seniors: Comfort, Care and a Better Quality of Life',
//                 'slug' => 'w',
//                 'excerpt' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'author_name' => 'No',
//                 'author_bio' => '',
//                 'summary' => 'How Assisted Living Improves Quality of Life for Seniors',
//                 'content' => '<p>Assisted living is aimed to support seniors who need help with daily activities while still allowing them to maintain their independence. It bridges the gap between living at home and receiving full-time medical care. The goal is simple: to improve quality of life while respecting each resident\'s lifestyle, preferences and individuality.</p><h2><strong>A Safe and Supportive Living Environment</strong></h2><p>Safety is one of the top concerns for seniors and their families. As people age, the risk of falls, accidents and medical emergencies increases. Assisted living communities are designed with elderly safety in mind.</p><p>At Hollywood Royale, living spaces are thoughtfully planned to reduce the difficulty and make movement easier. Handrails, proper lighting, emergency call systems and trained staff are available around the clock, helping residents feel safe and secure. Knowing that help is always nearby provides peace of mind not only to seniors but also to their families.</p><p>This safe environment allows seniors to move freely and confidently, without the constant fear of being alone during an emergency.</p><h2><strong>Personalized Help With Daily Activities</strong></h2><p>Daily tasks that once felt easy can become tiring or difficult with age. Assisted living provides support with activities such as bathing, dressing, grooming, medication reminders and mobility assistance.</p><p>At Hollywood Royale, care is never rushed or impersonal. Assistance is tailored to each resident\'s needs, ensuring they receive help only where required. This balance helps seniors maintain independence while avoiding frustration or exhaustion.</p><p>When daily routines become smoother, seniors have more energy and time to focus on enjoying their day rather than struggling through it.</p><h2><strong>Improved Physical Health and Wellness</strong></h2><p>Health is an essential foundation for a better quality of life. Assisted living supports seniors in maintaining better physical health through consistent routines, proper nutrition and access to care.</p>',
//                 'original_content' => null,
//                 'tags' => '["Beginner","Market"]',
//                 'keys' => null,
//                 'banner_image' => 'blog/banners/85VXxOrLDACOBHKPRATts04d7fHogjbgbhLa0WKq.png',
//                 'user_id' => 1,
//                 'blog_category_id' => 1,
//                 'read_time' => '5 min',
//                 'status' => 'draft',
//                 'featured' => 0,
//                 'seo_title' => 'w | Blog',
//                 'seo_description' => 'w',
//                 'seo_keywords' => 'Beginner',
//                 'publish_date' => '2026-01-30',
//                 'created_at' => '2026-01-31 06:40:33',
//                 'updated_at' => '2026-01-31 06:53:45',
//             ],
//         ]);
//     }
// }